# Generated by Django 4.2 on 2023-04-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suitable',
            field=models.CharField(default='7+', max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10),
        ),
    ]
